### ISSUE TITLE
Node frendly functions

### ISSUE THREAD

**Issue by 3y3** [afanasy/db3#19]
before example from your test.js

``` js

  before(function (done) {
    db.dropTable('test', function () {
      db.createTable('test', function () {
        db.dropTable('person', function () {
          db.createTable('person', ['id', 'name', 'gender'], function () {
            async.eachSeries(person, function (item, done) {db.insert('person', item, function () {done()})}, done)
          })
        })
      })
    })
  })
```

but users want to use `async` here:

``` js
before(function (done) {
  async.series([
    db.dropTable.bind(db, 'test'),
    db.createTable.bind(db, 'test'),
    db.dropTable.bind(db, 'person'),
    db.createTable.bind(db, 'person'),
    async.series.bind(async, person, db.insert.bind(db, 'person'));
  ], done);
});
```

this is impossible with your api, because you pass result as first arg, but node convention waits `err` as first argument.

After you start to support node style you feel free to add some other features to your functions call. It may be `promises` or `carreing`

For example after `carreing`, previous code will look like:

``` js
before(function (done) {
  async.series([
    db.dropTable('test'),
    db.createTable('test'),
    db.dropTable('person'),
    db.createTable('person'),
    async.eachSeries.bind(async, person, db.insert('person'));
  ], done);
});
```

Or shortly:

``` js
function series() {
  return async.series.bind.apply(async.series, [async].concat(arguments));
}
function map(obj, func) {
  return Object.keys(obj).map(function(key) {
    return func(obj[key]);
  })
}
before(series([
  db.dropTable('test'),
  db.createTable('test'),
  db.dropTable('person'),
  db.createTable('person'),
  series(map(person, db.insert('person')));
]));
```

Look at [ramda](http://ramdajs.com) if you want to expose functional programming api in your lib.

So using promises your `before` statement can look like:

``` js
before(function(done) {
  db.dropTable('test')
    .createTable('test')
    .dropTable('person')
    .createTable('person')
    .then(function(resolve, reject) {
      async.eachSeries(person, db.insert.bind(db, 'person'), function(err, result) {
        if (err) return reject(err);

        resolve(result)
      });
    })
    .then(done);
});
```

So keep in mind, that I don't read all your code at current time. This is only fast review and maybe I missed the main reason why you doesn't use node function style.

**Comment by afanasy** [comment]
Thanks for the detailed review!
I'm thinking about using promises or something else for calls chaining.
However, removing 'err' argument from the first place is done by design, since most of the time it's not used and just creating additional code bloating.

**Comment by afanasy** [comment]
Reverted to `err, data` node format in upcoming 2.0.0 version
